apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-sts
spec:
  serviceName: kafka-sts
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 3
      containers:
        - name: kafka
#          image: kafka -- хак чтобы не заморачиваться с настройками кафки (зоокипером итд)
          image: nginx
          ports:
            - name: http1
              containerPort: 8080
            - name: http2
              containerPort: 8080
          volumeMounts:
            - name: kafka-pvc
              mountPath: /var/data/
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
  volumeClaimTemplates:
    - metadata:
        name: kafka-pvc
      spec:
        storageClassName: yc-network-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi