apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: memcached
          image: memcached
          resources:
            requests:
              memory: "200Mi"
              cpu: "500m"
            limits:
              memory: "200Mi"
              cpu: "500m"
        - name: redis
          image: redis
          resources:
            requests:
              memory: "200Mi"
              cpu: "500m"
            limits:
              memory: "200Mi"
              cpu: "500m"