apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: bee42/whoami:2.2.0
          ports:
            - containerPort: 80
              name: web


