apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      usecase: loadbalancer
  template:
    metadata:
      labels:
        usecase: loadbalancer
    spec:
      containers:
        - image: nginx
          name: nginx