apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-taint
  labels:
    env: dp-taint
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx2-kub-16
          image: nginx
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      nodeSelector:
        usercase: workload
      tolerations:
        - effect: NoSchedule
          key: "dedicated"
          value: "true"
          operator: "Equal"