apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx-kub25
  policyTypes:
    - Ingress
  ingress:
