apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: local-http
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx-kub25
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              project: default
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80