apiVersion: v1
kind: Pod
metadata:
  name: nginx-kub25
  labels:
    app: nginx-kub25
spec:
  containers:
    - name: nginx-kub25
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
