apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-kub25
spec:
  containers:
    - name: ubuntu-kub25
      image: ubuntu
      command: ['/bin/sh', '-c', 'while true; do sleep 300; done']
      resources:
        limits:
          memory: "800Mi"
          cpu: "500m"
  restartPolicy: OnFailure
